# Generated by Django 4.1.1 on 2022-09-29 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_article_deleted_at_article_is_deleted'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
    ]
